name: Run the tests, build the image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      CONTAINER_REGISTRY_UN: ${{ secrets.CONTAINER_REGISTRY_UN }}
      CONTAINER_REGISTRY_PW: ${{ secrets.CONTAINER_REGISTRY_PW }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFG }}

      - name: Deploy
        run: ./deploy.sh


      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Build and push the image
        run: |
            docker login --username tno52 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
            docker build -t ghcr.io/tno52/practcium6:latest --file Dockerfile .  
            docker push ghcr.io/tno52/practcium6:latest

      - name: Azure Image
        run: |
          docker login --username $CONTAINER_REGISTRY_UN --password $CONTAINER_REGISTRY_PW $CONTAINER_REGISTRY
          docker tag ghcr.io/hbahramian/arithmetic-service:$VERSION $CONTAINER_REGISTRY/practicum6:$VERSION
          docker push $CONTAINER_REGISTRY/arithmetic-service:$VERSION